export const resume = {
  name: 'Peter Huang',
  role: 'Full Stack Developer',
  location: 'Calgary, AB',
  email: 'phuan516@mtroyal.ca',
  github: 'phuan516',
  linkedin: 'peter-huang-904b82164',
  intro:
    'Full Stack Developer with a proven track record in front-end and back-end development across JavaScript, TypeScript, ReactJS, and Python. I focus on optimizing web applications for performance and user experience, implementing robust coding practices, and introducing new technologies that streamline development workflows and enhance scalability. Experienced with cloud services across AWS and GCP.',
  status: 'Looking for work',
  about: [
    'Full Stack Developer based in Calgary, working across the front-end and back-end.',
    'Comfortable across JavaScript, TypeScript, Python, and Java — and the tooling around them.',
    'Recently focused on internal platform features, third-party integrations, and AI-assisted developer workflows.',
  ],
  experience: [
    {
      role: 'Full Stack Developer',
      company: 'Steelhaus Technologies',
      period: 'Mar 2025 — Apr 2026',
      location: 'Calgary, AB',
      bullets: [
        'Built features supporting employee compliance, training, certification, and maintenance workflows — streamlining oversight for 400+ employees and assets.',
        'Led development of a third-party HRIS integration connecting BambooHR and ADP Workforce Now, eliminating manual data entry.',
        'Introduced AI coding tools for rapid prototyping, cutting approval turnaround by ~2 weeks.',
        'Incorporated OHS requirements into incident reporting, reducing documentation time by 2–3 hours per incident.',
      ],
      stack: ['TypeScript', 'React', 'Node', 'AWS'],
    },
    {
      role: 'Full Stack Developer',
      company: 'Serenorty AI',
      period: 'May 2024 — Mar 2025',
      location: 'Remote',
      bullets: [
        'Adapted a React/Python app to Next.js, improving initial page load time and SEO.',
        'Introduced TypeScript across the team for improved type safety and code maintainability.',
        'Collaborated with the product team on roadmap and project deliverables.',
        'Designed and implemented UI layouts in Figma following Material Design best practices.',
      ],
      stack: ['Next.js', 'TypeScript', 'Python', 'Figma'],
    },
    {
      role: 'Product Process Specialist',
      company: 'Best Buy Canada',
      period: 'Nov 2024 — Mar 2025',
      location: 'Calgary, AB',
      bullets: [
        'Assisted customers with computer recommendations from 50+ options based on requirements and inventory.',
        'Processed incoming shipments of 1,500 items within the same day.',
        'Maintained store organization per floor plans for efficient product location.',
      ],
      stack: ['Customer Service', 'Logistics'],
    },
    {
      role: 'Full Stack Developer, Intern',
      company: 'Neo Financial',
      period: 'Jan 2022 — Aug 2022',
      location: 'Calgary, AB',
      bullets: [
        'Developed internal tools contributing to a 10% increase in developer productivity.',
        'Designed and built a web app tracking 200+ developers\' GitHub and Shortcut activities.',
        'Led an AWS pipeline monitoring tool trial with 30 developers across 5 teams.',
        'Redesigned UI based on feedback, reducing pipeline idle time by 70%.',
      ],
      stack: ['React', 'AWS', 'Node'],
    },
    {
      role: 'Project Manager, Intern',
      company: 'Alberta Health Services',
      period: 'Jan 2021 — Aug 2021',
      location: 'Calgary, AB',
      bullets: [
        'Led requirement gathering for Connect Care wave 2 deployment with hospital units and physicians.',
        'Oversaw tracking of service tickets, reducing ticket assessment time.',
        'Coordinated weekly developer meetings to address roadblocks and reduce delays.',
      ],
      stack: ['Project Management', 'Healthcare IT'],
    },
    {
      role: 'Junior Developer',
      company: 'Kent Imaging',
      period: 'Jul 2020 — Aug 2020',
      location: 'Calgary, AB',
      bullets: [
        'Independently learned and implemented React/TypeScript to port a mobile app login flow to a web application.',
      ],
      stack: ['React', 'TypeScript'],
    },
  ],
  projects: [
    {
      name: 'Ledger',
      blurb: 'A budget tracker that uses Google Sheets as the backend.',
      detail:
        'Sign in with Google, connect a spreadsheet, and track spending across categories, payment methods, and fixed expenses — your data stays entirely in your own Google account.',
      stack: ['TypeScript'],
      year: '2025',
      link: 'github.com/phuan516/Budget',
      status: 'Active',
    },
    {
      name: 'DevLog',
      blurb: 'Developer productivity tool tying Azure DevOps work items to Obsidian notes.',
      detail:
        'Pulls Azure DevOps work items alongside an Obsidian vault so context, decisions, and tickets live in one place.',
      stack: ['JavaScript'],
      year: '2025',
      link: 'github.com/phuan516/DevLog',
      status: 'Active',
    },
    {
      name: 'LiveTerm',
      blurb: 'My profile in a terminal-inspired interface.',
      detail:
        'Personal site rebuilt as an interactive terminal — runs commands, displays sections, and ships in a Docker image.',
      stack: ['TypeScript', 'Shell', 'Docker'],
      year: '2024',
      link: 'github.com/phuan516/LiveTerm-Personal',
      status: 'Active',
    },
    {
      name: '100 Weeks CSS',
      blurb: "Working through Matthias Martin's 100 days CSS challenge.",
      detail:
        'Pure-CSS scenes, animations, and illustrations — one entry per challenge prompt, in vanilla HTML/CSS/JS.',
      stack: ['HTML', 'CSS', 'JavaScript'],
      year: '2024',
      link: 'github.com/phuan516/100WeeksCSS',
      status: 'Archived',
    },
    {
      name: 'Commit Bot',
      blurb: 'A script that auto-adds, commits, and pushes — fill those green squares with one command.',
      detail:
        'Tiny shell utility for batch commit-and-push to a repo. Automates the boring parts of contribution-graph upkeep.',
      stack: ['Shell'],
      year: '2024',
      link: 'github.com/phuan516/commit-bot',
      status: 'Archived',
    },
    {
      name: 'Photo Search App',
      blurb: 'Image search app with modern UI and API integration.',
      detail: 'Front-end interview exercise — image search experience built with TypeScript and modern CSS.',
      stack: ['TypeScript', 'CSS'],
      year: '2023',
      link: 'github.com/phuan516/photo-search-interview-excerise',
      status: 'Archived',
    },
    {
      name: 'Mobile App Interface',
      blurb: 'Front-end hiring challenge showcasing mobile UI work.',
      detail: 'Mobile app interface design challenge — focus on layout fidelity and front-end fundamentals.',
      stack: ['HTML', 'CSS', 'JavaScript', 'SCSS'],
      year: '2023',
      link: 'github.com/phuan516/Frontend-Hiring-Challenge',
      status: 'Archived',
    },
    {
      name: 'Dev Utility App',
      blurb: 'A collection of personal automation and developer tools.',
      detail: "Catch-all repo for the small scripts and utilities that make a daily workflow smoother.",
      stack: ['TypeScript', 'JavaScript'],
      year: '2024',
      link: 'github.com/phuan516/random-stuff',
      status: 'Active',
    },
    {
      name: "Third Time's a Charm",
      blurb: 'Game-jam final project — built in Godot to learn a new engine.',
      detail:
        'Final project for a game development course. Chose Godot specifically to pick up a new language and engine inside the timebox.',
      stack: ['GDScript'],
      year: '2023',
      link: 'github.com/phuan516/third-times-a-charm',
      status: 'Archived',
    },
  ],
  education: [
    {
      school: 'Mount Royal University',
      degree: 'Bachelor of Computer Information Systems',
      period: '2017 — 2023',
      detail: 'Calgary, AB.',
    },
  ],
  skills: {
    Languages: ['JavaScript', 'TypeScript', 'Java', 'Python', 'HTML', 'CSS', 'SQL'],
    Frameworks: ['ReactJS', 'Next.js', 'GraphQL', 'REST API', 'Vue'],
    Tools: ['Figma', 'Jest', 'Git', 'GitHub', 'AWS', 'GCP', 'Vercel', 'Claude Code', 'Ollama', 'Azure DevOps', 'Jenkins'],
    Databases: ['MySQL', 'MongoDB', 'PostgreSQL'],
  },
}
